# Generated by Django 6.0.5 on 2026-05-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_kh', models.CharField(blank=True, max_length=255)),
                ('title_cn', models.CharField(blank=True, max_length=255)),
                ('short_en', models.TextField(blank=True)),
                ('short_kh', models.TextField(blank=True)),
                ('short_cn', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_kh', models.TextField(blank=True)),
                ('content_cn', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_news/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='company_news/videos/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
