# Generated by Django 6.0.5 on 2026-05-21 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynews',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_news/detail/'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_news/thumbnails/'),
        ),
        migrations.CreateModel(
            name='CompanyNewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='company_news/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='company_news.companynews')),
            ],
        ),
    ]
