# Generated by Django 6.0.5 on 2026-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_news', '0002_companynews_detail_image_alter_companynews_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynews',
            options={'ordering': ['-sort_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='companynews',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
